apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigquery-exporter-5m
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      run: bigquery-exporter
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
      labels:
        run: bigquery-exporter
    spec:
      containers:
      - name: bigquery-exporter
        image: us.gcr.io/sre-sandbox1/prometheus_bigquery_exporter:0.0.3
        args: [ "-project=prd-subscription",
                "-refresh=5m",
                "-logx.debug=true", 
                "-gauge-query=/queries/example/config/bq_successRate.sql",
              ]
        ports:
        - containerPort: 9050
        volumeMounts:
        - mountPath: /queries
          name: bigquery-config

      volumes:
      - name: bigquery-config
        configMap:
          name: bigquery-exporter-config
